### ISSUE TITLE
Phone input is not optional.

### ISSUE THREAD

**Issue by SireenAtGitHub** [SireenAtGithub/custom-invoice#9]
When a user is not sure about the client's phone number. the user ends up entering 123456780, 000000000 arbitrary numbers like this. 

To fix the issue we can put a check box right beneath the phone number input. and ask "Client doesn't have a mobile number?". and if a user checks that option we would simply disable the phone number input and make no validation on the same input.

It will require front-end as well as back-end changes. in the back end, there is a value that is static to all numbers ( +91 ). so if the no phone number check happens it needs to be handled as well.

The question here is what we should display on the invoice. What will be the ideal options? is it NA or blank space only?

@kiteretsu-daihyakka - put out some thoughts on questions to be asked in the checkbox and on the invoice phone number value.

**Comment by kiteretsu-daihyakka** [comment]
For phone number, how about putting (Optional) text as shown below, 
![phoneNoOptional](https://user-images.githubusercontent.com/61159866/167249735-d6eb2896-ab96-4bb4-8f97-27c1aae019ed.png).
And, For +91 we can put the condition to add '+91' only when 'phone' key is present in request.data, below is one reference link for that technique,
=> https://stackoverflow.com/questions/6362047/how-to-check-if-a-name-value-pair-exists-when-posting-data

And in invoice blank space is fine.

Also i believe we need to mark phone field as null=True in model otherwise serializer will give error.

**Comment by SireenAtGitHub** [comment]
I believe in the technique you have provided. I will make check, if the phone no is empty I would not print +91 and the phone number field in invoice would empty. 

I will start working on the issue soon. On the front-end or condition can be utilised. we allow null or the value of 10 digits only.

**Comment by kiteretsu-daihyakka** [comment]
Sure, work on it!

**Comment by kiteretsu-daihyakka** [comment]
We can allow null at model level, It's fine. Doing so, we can just neglect phone parameter from the body {} in $.ajax IF the phone field is empty.

**Comment by SireenAtGitHub** [comment]
Starting the work
